AWSTemplateFormatVersion: "2010-09-09"
Resources:
  FetchLatestResources:
    Type: "Custom::FetchLatestResources"
    Properties:
      ServiceToken: arn:aws:lambda:ap-south-2:youraccountnumber:function:FetchLatestEc2TestServer

  MyVolume:
    Type: AWS::EC2::Volume
    Properties:
      AvailabilityZone: ap-south-2b
      SnapshotId: !GetAtt FetchLatestResources.SnapshotId
      Tags:
      - Key: Name
        Value: MyVolume

  MyEc2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !GetAtt FetchLatestResources.AmiId
      PrivateIpAddress: 172.31.35.25
      InstanceType: t3.micro
      KeyName: adminaccess
      AvailabilityZone: ap-south-2b
      Volumes:
      - Device: "/dev/sda2"
        VolumeId: !Ref MyVolume
      Tags:
      - Key: Name
        Value: Test_AppServer
      SecurityGroups:
      - Fn::ImportValue: MyExportedSecurityGroupNameThirdAws
      - Fn::ImportValue: MyExportedSecurityGroupNameSevenAws
      - Fn::ImportValue: MyExportedSecurityGroupNameFourthAws
