AWSTemplateFormatVersion: "2010-09-09"
Description: Security group for app server
Resources:
    mob_pgm_all:
        Type: AWS::EC2::SecurityGroup
        Properties:
                VpcId: vpc-0c34137c6a24580a0  #hyderabad's default vpc
                #outbound rules
                SecurityGroupEgress:    
                  -   CidrIp: 202.88.154.70/32
                      Description:   Remote
                      #DestinationPrefixListId: String
                      #DestinationSecurityGroupId: String
                      FromPort: 3389
                      IpProtocol: tcp
                      ToPort: 3389
                  -   CidrIp: 0.0.0.0/32
                      Description:   all outbound access
                      #DestinationPrefixListId: String
                      #DestinationSecurityGroupId: String
                      FromPort: 443
                      IpProtocol: tcp
                      ToPort: 443
                #inbound rules
                SecurityGroupIngress:
                  - IpProtocol: tcp
                    FromPort: 443
                    ToPort: 443
                    CidrIp: 61.0.40.203/32
                    Description: Jath ho

