AWSTemplateFormatVersion: "2010-09-09"
Description: Rds oracle database

#Parameters:

Resources:
  RDS:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: MyDBInstancetest
      AvailabilityZone: ap-south-2a #hyderabad
      DBName: EBANK
      MultiAZ: false
      StorageType: gp2
      MasterUsername: admin
      MasterUserPassword: "12345678"
      Engine: oracle-se2
      AllocatedStorage: 110
       PubliclyAccessible: true
      DBInstanceClass: db.m5.large
      VPCSecurityGroups:
      - sg-03f08be106e97ec74
      EngineVersion: 19.0.0.0.ru-2023-07.rur-2023-07.r1
      port: 8805
      EnablePerformanceInsights: true #Enable Performance Insights
      PerformanceInsightsRetentionPeriod: 7
      BackupRetentionPeriod: 1
      #AutomaticBackupReplicationRegion: us-west-2
      #BackupWindow: "01:00-02:00" 
      KmsKeyId: arn:aws:kms:ap-south-2:378424009885:key/155fb0ae-e3a8-468d-83ef-ca4e17e44cee  #hyderabad region kms arn
      StorageEncrypted: true
      AutoMinorVersionUpgrade: false
      DeletionProtection: true
      LicenseModel: license-included
      #DeletionPolicy: Retain #means even if you delete the stack of cform you need to manually delete rds 
      Tags:
      - Key: Env
        Value: Prod(DR)

