AWSTemplateFormatVersion: "2010-09-09"
Description: Rds oracle database

#Parameters:

Resources:
  RDS:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: MyDBInstancetest
      AvailabilityZone: ap-south-1a #mumbai
      DBName: ebanking
      StorageType: gp2
      MasterUsername: admin
      MasterUserPassword: "12345678"
      Engine: oracle-se2
      AllocatedStorage: 100
      DBInstanceClass: db.m5.large
      VPCSecurityGroups:
      - sg-03f08be106e97ec74
      EngineVersion: 19.0.0.0.ru-2024-01.rur-2024-01.r1
      #port: '1521'
      EnablePerformanceInsights: true #Enable Performance Insights
      PerformanceInsightsRetentionPeriod: 7
      BackupRetentionPeriod: 1
      #AutomaticBackupReplicationRegion: us-west-2
      #BackupWindow: "01:00-02:00" 
      KmsKeyId: arn:aws:kms:ap-south-1:533266960972:key/12198d73-ed12-4eaa-a4b5-d3153202ab08
      StorageEncrypted: true
      AutoMinorVersionUpgrade: false
      DeletionProtection: true
      LicenseModel: license-included
      #DeletionPolicy: Retain #means even if you delete the stack of cform you need to manually delete rds 
      Tags:
      - Key: Env
        Value: Prod

