AWSTemplateFormatVersion: "2010-09-09"
Description: Rds oracle database

#Parameters:

Resources:  
    RDS:
      Type: AWS::RDS::DBInstance
      Properties:
        AvailabilityZone: us-west-2a
        DBName: ebankingrds
        StorageType: gp2 
        MasterUsername: admin
        MasterUserPassword: "12345678"
        Engine: oracle-se2
        VPCSecurityGroups: default
        AllocatedStorage: 100
        DBInstanceClass: db.m5.large
        VPCSecurityGroups: sg-081787a4571bd9c08
        EngineVersion: 19.0.0.0.ru-2024-01.rur-2024-01.r1
        port: '3306'
        EnablePerformanceInsights: true  #Enable Performance Insights
        PerformanceInsightsRetentionPeriod: 7
        BackupRetentionPeriod: 1
        #AutomaticBackupReplicationRegion: us-west-2
        #BackupWindow: "01:00-02:00" 
        KmsKeyId: arn:aws:kms:us-west-2:533266960972:key/d7d2ab36-7a50-4cd4-978a-41054f493e5c
        AutoMinorVersionUpgrade: false
        DeletionProtection: true
        #DeletionPolicy: Retain #means even if you delete the stack of cform you need to manually delete rds 
        Tags: 
            - Key: Env
              value: Prod
         
