AWSTemplateFormatVersion: '2010-09-09'
Description: Template to create an Elastic IP for mobile app

Resources:
  MyEip:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc

Outputs:
  ElasticIPAddress:
    Description: The allocated Elastic IP address for Mobile App
    Value: !Ref MyEip
    Export:
      Name: MyExportedMobileAppEip
