AWSTemplateFormatVersion: "2010-09-09"
Description: Rds oracle database

#Parameters:

Resources:
  RDS:
    Type: AWS::RDS::DBInstance
    Properties:
      DBSnapshotIdentifier: arn:aws:rds:ap-south-2:378424009885:snapshot:latest-ebank-snapshot
      DBInstanceIdentifier: ebank
      AvailabilityZone: ap-south-2b #hyderabad
      DBName: EBANK
      MultiAZ: false
      StorageType: gp2
      MasterUsername: admin
      MasterUserPassword: "Supertech1"
      Engine: oracle-se2
      AllocatedStorage: 110
      MaxAllocatedStorage:  200
      #EnableStorageAutoResize: true
      PubliclyAccessible: true
      DBInstanceClass: db.r6i.large
      VPCSecurityGroups:
      - Fn::ImportValue: MyExportedSecurityGroupIdSecond
      - Fn::ImportValue: MyExportedSecurityGroupIdFifth
      - Fn::ImportValue: MyExportedSecurityGroupIdSixth
      - Fn::ImportValue: MyExportedSecurityGroupIdNinth
      # - Fn::ImportValue: MyExportedSecurityGroupNameSecond
      # - Fn::ImportValue: MyExportedSecurityGroupNameFifth
      
      EngineVersion: 19.0.0.0.ru-2023-07.rur-2023-07.r1
      #port: 8805
      EnablePerformanceInsights: true #Enable Performance Insights
      PerformanceInsightsRetentionPeriod: 7
      BackupRetentionPeriod: 15
      #AutomaticBackupReplicationRegion: ap-south-2
      PreferredBackupWindow: "01:00-01:30" 
      KmsKeyId: arn:aws:kms:ap-south-2:378424009885:key/021f8050-1f55-42a5-ac94-9ec55a1ad03b  #hyderabad region kms arn
      StorageEncrypted: true
      AutoMinorVersionUpgrade: false
      DeletionProtection: true
      #CACertificateIdentifier: rds-ca-2019          need to check if any error persists.
      LicenseModel: license-included
      CopyTagsToSnapshot: true
      #DeletionPolicy: Retain #means even if you delete the stack of cform you need to manually delete rds 
      Tags:
      - Key: Env
        Value: Prod